name: Publish to pub.dev

on:
  push:
    branches: [ develop, 'release/[0-9]+.[0-9]+.[0-9]+']
  pull_request:
    branches: [ develop, 'release/[0-9]+.[0-9]+.[0-9]+']

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Check for warnings
        run: flutter analyze

    #   - name: Run tests
    #     run: flutter test